# terraform/secrets.tf

# 1. Générer un mot de passe aléatoire pour MongoDB
resource "random_password" "mongodb_password" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# 2. Stocker les credentials dans AWS Secrets Manager
resource "aws_secretsmanager_secret" "mongodb_credentials" {
  name        = "lab-mongodb-credentials"
  description = "MongoDB admin credentials - Generated by Terraform"
  
  tags = {
    Name        = "MongoDB Credentials"
    Environment = "lab"
  }
}

resource "aws_secretsmanager_secret_version" "mongodb_credentials" {
  secret_id = aws_secretsmanager_secret.mongodb_credentials.id
  secret_string = jsonencode({
    username = "admin"
    password = random_password.mongodb_password.result
  })
}

# Créer le secret dans AWS Secrets Manager
resource "aws_secretsmanager_secret" "mongodb_uri" {
  name        = "lab-mongodb-uri"
  description = "MongoDB connection URI"
  
  tags = {
    Name = "MongoDB URI"
  }
}


locals {
  mongodb_user           = "admin"
  mongodb_password_raw   = random_password.mongodb_password.result
  mongodb_password_enc   = urlencode(local.mongodb_password_raw) # <-- encodage (ex: @ -> %40, + -> %2B, etc.)
  mongodb_uri_value      = "mongodb://${local.mongodb_user}:${local.mongodb_password_enc}@${aws_instance.mongodb.private_ip}:27017/"
}

# Stocker la valeur du secret
resource "aws_secretsmanager_secret_version" "mongodb_uri" {
  secret_id = aws_secretsmanager_secret.mongodb_uri.id
  secret_string = jsonencode({
    MONGODB_URI = local.mongodb_uri_value
  })
}

# IAM Policy pour permettre à EKS de lire le secret
resource "aws_iam_policy" "eks_secrets_policy" {
  name        = "eks-secrets-access"
  description = "Allow EKS pods to read secrets from Secrets Manager"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "secretsmanager:GetSecretValue",
          "secretsmanager:DescribeSecret"
        ]
        Resource = aws_secretsmanager_secret.mongodb_uri.arn
      }
    ]
  })
}

# Attacher la policy au rôle des nodes EKS
resource "aws_iam_role_policy_attachment" "eks_secrets" {
  policy_arn = aws_iam_policy.eks_secrets_policy.arn
  role       = module.eks.eks_managed_node_groups["main"].iam_role_name
}